In [60]:
import json
%matplotlib inline
import os
import pandas as pd

In [6]:
os.getcwd()

'/Users/sakthivelsabapathy/Desktop/python-projects/capital-one'

In [38]:

data=pd.read_json('./data/transactions.txt',lines=True)

In [39]:
data

,accountNumber,accountOpenDate,acqCountry,availableMoney,cardCVV,cardLast4Digits,cardPresent,creditLimit,currentBalance,currentExpDate,...,merchantName,merchantState,merchantZip,posConditionCode,posEntryMode,posOnPremises,recurringAuthInd,transactionAmount,transactionDateTime,transactionType
0,737265056,2015-03-14,US,5000.00,414,1803,False,5000,0.00,06/2023,...,Uber,,,01,02,,,98.55,2016-08-13T14:27:32,PURCHASE
1,737265056,2015-03-14,US,5000.00,486,767,True,5000,0.00,02/2024,...,AMC #191138,,,01,09,,,74.51,2016-10-11T05:05:54,PURCHASE
2,737265056,2015-03-14,US,5000.00,486,767,False,5000,0.00,08/2025,...,Play Store,,,01,09,,,7.47,2016-11-08T09:18:39,PURCHASE
3,737265056,2015-03-14,US,5000.00,486,767,False,5000,0.00,08/2025,...,Play Store,,,01,09,,,7.47,2016-12-10T02:14:50,PURCHASE
4,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,10/2029,...,Tim Hortons #947751,,,01,02,,,71.18,2016-03-24T21:04:46,PURCHASE
5,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,01/2020,...,In-N-Out #422833,,,01,02,,,30.76,2016-04-19T16:24:27,PURCHASE
6,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,05/2020,...,Krispy Kreme #685312,,,01,02,,,57.28,2016-05-21T14:50:35,PURCHASE
7,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,01/2021,...,Shake Shack #968081,,,01,05,,,9.37,2016-06-03T00:31:21,PURCHASE
8,830329091,2015-08-06,,4990.63,885,3143,True,5000,9.37,08/2032,...,Burger King #486122,,,01,02,,,523.67,2016-06-10T01:21:46,PURCHASE
9,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,04/2020,...,Five Guys #510989,,,08,05,,,164.37,2016-07-11T10:47:16,PURCHASE
10,830329091,2015-08-06,US,5000.00,885,3143,True,5000,0.00,05/2023,...,Auntie Anne's #747964,,,08,02,,,160.18,2016-09-07T20:22:47,PURCHASE
11,830329091,2015-08-06,US,5000.00,885,3143,False,5000,0.00,08/2024,...,GreenCook,,,01,09,,,40.75,2016-12-07T16:34:04,PURCHASE
12,830329091,2015-08-06,US,4959.25,885,3143,False,5000,40.75,08/2024,...,GreenCook,,,01,09,,,40.75,2016-12-14T10:00:35,PURCHASE
13,830329091,2015-08-06,US,4918.50,885,3143,False,5000,81.50,08/2024,...,GreenCook,,,01,09,,,40.75,2016-12-20T18:38:23,PURCHASE
14,830329091,2015-08-06,US,4877.75,885,3143,False,5000,122.25,08/2024,...,GreenCook,,,01,09,,,40.75,2016-12-28T06:43:01,PURCHASE
15,574788567,2015-10-13,US,2500.00,206,8522,True,2500,0.00,12/2031,...,Washington Repair,,,01,02,,,30.08,2016-01-02T11:19:46,PURCHASE
16,574788567,2015-10-13,US,2469.92,206,8522,True,2500,30.08,09/2027,...,Eazy Tire,,,01,09,,,41.25,2016-01-16T01:01:27,PURCHASE
17,574788567,2015-10-13,US,2428.67,206,8522,False,2500,71.33,08/2025,...,Convenient Auto Services,,,01,09,,,0.00,2016-01-26T14:04:22,ADDRESS_VERIFICATION
18,574788567,2015-10-13,US,2428.67,579,4219,True,2500,71.33,08/2032,...,Convenient Auto Services,,,01,05,,,124.21,2016-01-29T07:17:39,PURCHASE
19,574788567,2015-10-13,US,2304.46,579,4219,True,2500,195.54,08/2022,...,Shell Auto Body,,,01,09,,,196.07,2016-01-29T07:33:15,PURCHASE
20,574788567,2015-10-13,US,2108.39,579,4219,True,2500,391.61,11/2027,...,Convenient Auto Services,,,01,05,,,4.11,2016-01-29T21:44:33,PURCHASE
21,574788567,2015-10-13,US,2500.00,206,8522,True,2500,0.00,08/2028,...,Fast Auto Services,,,01,09,,,108.86,2016-02-06T08:16:46,PURCHASE
22,574788567,2015-10-13,US,2391.14,579,4219,True,2500,108.86,09/2032,...,Washington Repair,,,01,05,,,28.23,2016-02-12T03:47:24,PURCHASE
23,574788567,2015-10-13,US,2362.91,579,4219,True,2500,137.09,10/2028,...,Washington Repair,,,01,02,,,26.17,2016-02-22T17:32:13,PURCHASE
24,574788567,2015-10-13,US,2336.74,206,8522,False,2500,163.26,12/2021,...,staples.com,,,01,02,,,215.16,2016-02-28T15:53:52,PURCHASE
25,574788567,2015-10-13,US,2121.58,579,4219,True,2500,378.42,06/2033,...,Convenient Repair,,,01,09,,,15.83,2016-02-28T16:43:46,PURCHASE
26,574788567,2015-10-13,US,2500.00,579,4219,True,2500,0.00,12/2019,...,Shell Repair,,,01,02,,,35.14,2016-03-02T21:49:24,PURCHASE
27,574788567,2015-10-13,US,2464.86,579,4219,True,2500,35.14,03/2024,...,Shell Auto Body,,,08,09,,,24.44,2016-03-05T22:24:50,PURCHASE
28,574788567,2015-10-13,US,2440.42,579,4219,True,2500,59.58,08/2032,...,Eazy Repair,,,01,05,,,139.44,2016-03-09T14:41:15,PURCHASE
29,574788567,2015-10-13,US,2300.98,206,8522,True,2500,199.02,10/2024,...,Fast Repair,,,01,80,,,235.74,2016-03-10T00:59:51,PURCHASE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786333,732852505,2012-08-23,US,48834.39,936,3783,True,50000,1165.61,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-09-29T05:52:39,PURCHASE
786334,732852505,2012-08-23,US,50000.00,936,3783,False,50000,0.00,04/2029,...,Uber,,,01,05,,,103.58,2016-10-05T04:24:35,PURCHASE
786335,732852505,2012-08-23,US,49896.42,936,3783,True,50000,103.58,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-10-13T16:19:04,PURCHASE
786336,732852505,2012-08-23,US,49844.94,939,3388,True,50000,155.06,08/2028,...,Starbucks #102806,,,01,02,,,46.20,2016-10-13T22:10:45,PURCHASE
786337,732852505,2012-08-23,US,49798.74,939,3388,False,50000,201.26,08/2023,...,hulu.com,,,01,09,,,18.89,2016-10-26T11:12:21,PURCHASE
786338,732852505,2012-08-23,US,49779.85,936,3783,True,50000,220.15,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-10-27T08:12:57,PURCHASE
786339,732852505,2012-08-23,US,49728.37,939,3388,False,50000,271.63,03/2029,...,Lyft,,,01,09,,,89.18,2016-10-29T03:15:19,PURCHASE
786340,732852505,2012-08-23,US,49639.19,939,3388,True,50000,360.81,08/2029,...,AMC #128743,,,01,05,,,10.94,2016-10-31T02:08:05,PURCHASE
786341,732852505,2012-08-23,US,50000.00,936,3783,True,50000,0.00,10/2029,...,AMC #128743,,,01,05,,,283.38,2016-11-08T20:41:41,PURCHASE
786342,732852505,2012-08-23,US,49716.62,936,3783,True,50000,283.38,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-11-09T13:58:47,PURCHASE
786343,732852505,2012-08-23,US,49665.14,939,3388,False,50000,334.86,03/2025,...,Uber,,,01,09,,,86.55,2016-11-11T18:46:26,PURCHASE
786344,732852505,2012-08-23,US,49578.59,936,3783,False,50000,421.41,09/2029,...,Lyft,,,01,09,,,11.38,2016-11-12T16:11:33,PURCHASE
786345,732852505,2012-08-23,US,49567.21,939,3388,False,50000,432.79,01/2033,...,Uber,,,08,05,,,30.97,2016-11-15T12:42:26,PURCHASE
786346,732852505,2012-08-23,US,49536.24,936,3783,True,50000,463.76,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-11-22T19:30:16,PURCHASE
786347,732852505,2012-08-23,US,49484.76,936,3783,False,50000,515.24,09/2024,...,Lyft,,,08,05,,,233.04,2016-11-24T21:17:47,PURCHASE
786348,732852505,2012-08-23,US,49251.72,939,3388,False,50000,748.28,08/2023,...,hulu.com,,,01,09,,,18.89,2016-11-25T13:39:10,PURCHASE
786349,732852505,2012-08-23,US,49232.83,939,3388,True,50000,767.17,03/2023,...,AMC #145832,,,01,02,,,61.21,2016-11-28T04:20:08,PURCHASE
786350,732852505,2012-08-23,US,50000.00,936,3783,True,50000,0.00,12/2025,...,EZ Putt Putt #804489,,,01,09,,,78.09,2016-12-01T17:33:17,PURCHASE
786351,732852505,2012-08-23,US,49921.91,936,3783,False,50000,78.09,04/2023,...,Uber,,,01,90,,,73.56,2016-12-05T14:58:37,PURCHASE
786352,732852505,2012-08-23,US,49848.35,936,3783,True,50000,151.65,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-12-07T14:05:14,PURCHASE
786353,732852505,2012-08-23,US,49796.87,936,3783,True,50000,203.13,06/2029,...,EZ Putt Putt #804489,,,01,09,,,190.41,2016-12-10T12:24:38,PURCHASE
786354,732852505,2012-08-23,US,49606.46,939,3388,True,50000,393.54,12/2030,...,KFC #206511,,,08,05,,,83.97,2016-12-10T23:29:11,PURCHASE
786355,732852505,2012-08-23,US,49522.49,936,3783,False,50000,477.51,08/2029,...,Uber,,,01,09,,,157.22,2016-12-18T14:06:34,PURCHASE
786356,732852505,2012-08-23,US,49365.27,939,3388,False,50000,634.73,06/2021,...,Lyft,,,01,09,,,408.83,2016-12-19T03:25:53,PURCHASE
786357,732852505,2012-08-23,US,48956.44,936,3783,True,50000,1043.56,07/2032,...,Sunoco Gas #380975,,,08,05,,,51.48,2016-12-22T07:27:23,PURCHASE
786358,732852505,2012-08-23,US,48904.96,936,3783,False,50000,1095.04,12/2022,...,Lyft,,,01,90,,,119.92,2016-12-22T18:44:12,PURCHASE
786359,732852505,2012-08-23,US,48785.04,939,3388,False,50000,1214.96,08/2023,...,hulu.com,,,01,09,,,18.89,2016-12-25T16:20:34,PURCHASE
786360,732852505,2012-08-23,US,48766.15,936,3783,False,50000,1233.85,08/2025,...,Lyft,,,01,02,,,49.43,2016-12-27T15:46:24,PURCHASE
786361,732852505,2012-08-23,US,48716.72,939,3388,False,50000,1283.28,07/2022,...,walmart.com,,,99,09,,,49.89,2016-12-29T00:30:55,PURCHASE
786362,732852505,2012-08-23,US,48666.83,939,3388,False,50000,1333.17,05/2024,...,Uber,,,01,05,,,72.18,2016-12-30T20:10:29,PURCHASE

In [10]:
data.columns.to_list

<bound method Index.tolist of Index([u'accountNumber', u'accountOpenDate', u'acqCountry', u'availableMoney',
       u'cardCVV', u'cardLast4Digits', u'cardPresent', u'creditLimit',
       u'currentBalance', u'currentExpDate', u'customerId',
       u'dateOfLastAddressChange', u'echoBuffer', u'enteredCVV',
       u'expirationDateKeyInMatch', u'isFraud', u'merchantCategoryCode',
       u'merchantCity', u'merchantCountryCode', u'merchantName',
       u'merchantState', u'merchantZip', u'posConditionCode', u'posEntryMode',
       u'posOnPremises', u'recurringAuthInd', u'transactionAmount',
       u'transactionDateTime', u'transactionType'],
      dtype='object')>

In [87]:
print(data['merchantZip']).describe()

count     786363
unique         1
top
freq      786363
Name: merchantZip, dtype: object

In [86]:
data['merchantZip'].nunique()

1

In [61]:
# check for null values in the various column. 
print("No. of Null Values inside data:", data.isnull().sum())

('No. of Null Values inside data:', accountNumber               0
accountOpenDate             0
acqCountry                  0
availableMoney              0
cardCVV                     0
cardLast4Digits             0
cardPresent                 0
creditLimit                 0
currentBalance              0
currentExpDate              0
customerId                  0
dateOfLastAddressChange     0
echoBuffer                  0
enteredCVV                  0
expirationDateKeyInMatch    0
isFraud                     0
merchantCategoryCode        0
merchantCity                0
merchantCountryCode         0
merchantName                0
merchantState               0
merchantZip                 0
posConditionCode            0
posEntryMode                0
posOnPremises               0
recurringAuthInd            0
transactionAmount           0
transactionDateTime         0
transactionType             0
dtype: int64)

In [ ]:
#accountOpenDate,acqCountry,availableMoney,cardPresent,creditLimit,currentBalance,currentExpDate,dateOfLastAddressChange
#expirationDateKeyInMatch,isFraud,merchantCategoryCode,merchantCategoryCode,merchantCountryCode,merchantName
#'merchantState', u'merchantZip', u'posConditionCode', u'posEntryMode','posOnPremises', u'recurringAuthInd', u'transactionAmount'
#'transactionDateTime', u'transactionType'